#!/usr/bin/env python

"""
Phase 2 data script

Contains functions for performance data acquisition and analysis of
phase 2 experiments.

Functions:
- test_trial() -- Tests performance of one trial
- test_multiple_trials() -- Tests performance of multiple trials and
  saves data to file
- check_completion() -- Check which trials completed the goal
- check_completion_ratio() -- Returns the number of successful trials
  and ratio
- check_completion_time() -- Returns the average number of steps
  required to complete the goal in an experiment for the system version
- plot_completion_times() -- Plots the completion times for the system
  versions in the different experiments
"""

import numpy as np

import phase_2


def test_trial(model_type, trial_number, number_of_simulations):
    """Test performance of one trial

    Keyword arguments:
    - model_type (string) -- The model type (run in phase 1) to test
    - trial_number (string) -- The trial number (run in phase 1) to
      test
    - number_of_simulations (int) -- desired number of simulations

    Tests the goal based planner by running a desired number of
    simulations and returning data on goal accomplishment and
    number of required steps for goal based planning and data on reward
    for utility reasoning experiments. Set graphics_on to False in
    phase_2.py for much faster runtime.
    """
    trial_data = []
    for simulation_number in range(number_of_simulations):
        simulation_data = phase_2.main(model_type, trial_number)
        trial_data.append(simulation_data)

    return np.array(trial_data)


def test_multiple_trials(model_type, trials, number_of_simulations):
    """Test performance of multiple trials

    Keyword arguments:
    - model_type (string) -- The model type (run in phase 1) to test
    - trials (range of ints) -- The trials (run in phase 1) to test
    - number_of_simulations (int) -- desired number of simulations per
      trial

    Tests all the trials by running a desired number of simulations
    for each in the current scenario and returns data array in which
    first column is goal accomplished yes/no (1/0) and second
    column is number of required steps for completion in the case of
    goal based planning. For utility reasoning experiments, the data
    array contains data on acquired utility. Set graphics_on to False
    in phase_2.py for much faster runtime.
    """
    model_data = []
    for trial_number in trials:
        trial_data = test_trial(model_type, trial_number,
                                number_of_simulations
                                )
        model_data.append(trial_data)

    return np.array(model_data)


def check_completion_ratio(multiple_trials_data):
    """Check ratio of successful trials

    Keyword arguments:
    - multiple_trials_data -- data as generated by function
      test_multiple_trials()

    Returns the number of successful trials and ratio of successful
    trials.
    """
    number_of_trials = multiple_trials_data.shape[0]
    number_of_simulations = multiple_trials_data.shape[1]
    completion_data = multiple_trials_data[:, :, 0]
    complete_simulations = np.count_nonzero(completion_data, 1)
    condition = complete_simulations >= 0.9 * number_of_simulations
    complete_trials = len(np.where(condition)[0])
    completion_ratio = complete_trials / number_of_trials

    return (complete_trials, completion_ratio)


def get_successful_trials(multiple_trials_data):
    """Returns data array with successful trials

    Keyword arguments:
    - multiple_trials_data -- data as generated by function
      test_multiple_trials()

    Checks which of the trials completed the goal in more than 90%
    of the simulation runs. Returns data array of successful trials.
    """
    return


def check_completion_time(successful_trials_data):
    """Check runtime of successful trials

    Keyword arguments:
    - successful_trials_data -- data as generated by function
      check_accomplished()

    Calculates the number or required steps for accomplishing goal
    averaged over all simulations of system version. Returns average
    number of steps and standard deviation.
    """
    return


def plot_completion_times(number_of_experiments):
    """Plot completion times

    Loads data files for each system version and plots the completion
    times in the different experiments.
    """
    return


if __name__ == '__main__':
    # TESTS
#    data = test_trial('IGN', '6', 100)
    data = test_multiple_trials('FIX', range(1, 11), 10)
    (complete_simulations, completion_ratio) = check_completion_ratio(data)
